Items:
- Name: Youtube
  RegExp: ^__TIME[UNIXTIME]__\t__COMMENT__$
- Name: Twitcasting
  RegExp: ^\[__TIME[2006/01/02 15:04:05]__\] __COMMENT__（.*$
- Name: Ustream
  RegExp: ^__TIME[15:04:05]__ \(.+?\) __COMMENT__$
- Name: Openrec
  RegExp: '^.*?"message": "__COMMENT__".*?"cre_dt": "__TIME[2006\-01\-02 15:04:05]__".*?$'
